### ISSUE TITLE
Cannot parse programs with dashes and double dashes as arguments

### ISSUE THREAD

**Issue by rkrp** [mattjegan/HowLong#15]
Currently, we are not capable of spawning programs which takes arguments in the form of dashes or double dashes, (example: `ls -a`)

Running 

```
howlong "ls -a"
```

results in 

```
Running ls -a
Traceback (most recent call last):
  File "/usr/bin/howlong", line 11, in <module>
    load_entry_point('howlong==0.0.1', 'console_scripts', 'howlong')()
  File "/usr/lib/python3.5/site-packages/HowLong/HowLong.py", line 35, in howlong
    HowLong().run()
  File "/usr/lib/python3.5/site-packages/HowLong/HowLong.py", line 25, in run
    process = Popen(self.parsed_args.command)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'ls -a'
```

and running

```
howlong ls -a
```

results in 

```
usage: howlong [-h] [-i [interval]] C [C ...]
howlong: error: unrecognized arguments: -a
```

We can make use of `argparse.REMAINDER` for `nargs` to get all the arguments for the target program properly. 

Would like to hear your thoughts before I can send a PR 😄

**Comment by mattjegan** [comment]
Thanks for the report @rkrp. I'm happy for you to submit a PR if you can ensure everything still works as expected 😄

**Comment by rkrp** [comment]
Sent a PR #16

**Comment by mattjegan** [comment]
Thanks again
